import { Product, Category, WebsiteSettings, Coupon, Review, MediaItem, Customer, Order } from '../types';

export const DEFAULT_SETTINGS: WebsiteSettings = {
  websiteName: 'VELORA',
  tagline: 'Everyday Essentials, Elevated.',
  logo: '',
  favicon: '⚡',
  heroBadge: 'PREMIUM COLLECTION 2026',
  heroTitle: 'Everyday Essentials, Elevated.',
  heroDescription: 'Discover high-precision kitchen technology, master-crafted organic harvests, signature minimalist apparel, and clinically tested daily wellness formulas.',
  heroImage: 'https://images.unsplash.com/photo-1544816155-12df9643f363?auto=format&fit=crop&w=1200&q=80',
  heroCtaText: 'Explore Collection',
  heroCtaLink: '#categories',
  heroFeaturedProductId: 'prod-cooker-1',
  primaryColor: '#d4af37',
  secondaryColor: '#0c0d12',
  footerText: '© 2026 VELORA Luxury E-Commerce Inc. Engineered with precision. All rights reserved.',
  phone: '+880 1800-835672',
  email: 'concierge@velora-luxury.com',
  address: 'Plot 28, Avenue 9, Banani Commercial Area, Dhaka 1213',
  currencySymbol: '৳',
  deliveryDhaka: 60,
  deliveryOutsideDhaka: 120,
  socialLinks: {
    facebook: 'https://facebook.com/veloraluxury',
    instagram: 'https://instagram.com/veloraluxury',
    tiktok: 'https://tiktok.com/@veloraluxury',
    youtube: 'https://youtube.com/@veloraluxury',
  },
  specialOffer: {
    enabled: true,
    badge: 'FLASH SALE • LIMITED QUANTITY',
    title: 'UPGRADE YOUR EVERYDAY LIVING',
    description: 'Experience the 2026 Flagship Smart Induction Multi-Cooker alongside our Wild Sundarbans Raw Forest Reserve Honey at an exclusive promotional rate.',
    discount: '30% OFF',
    productId: 'prod-cooker-1',
    endDate: new Date(Date.now() + 5 * 24 * 60 * 60 * 1000).toISOString(),
    buttonText: 'Claim Special Offer',
    buttonLink: '/shop?category=Cooker%20%26%20Rice%20Items',
    image: 'https://images.unsplash.com/photo-1584269600464-37b1b58a9fe7?auto=format&fit=crop&w=1000&q=80',
  },
  sections: {
    hero: true,
    categories: true,
    featuredProducts: true,
    showcase3D: true,
    specialOffer: true,
    whyChooseUs: true,
    reviews: true,
    newsletter: true,
    footer: true,
  },
};

export const DEFAULT_CATEGORIES: Category[] = [
  {
    id: 'cat-1',
    name: 'Cooker & Rice Items',
    slug: 'cooker-rice-items',
    description: 'Advanced IH induction smart cookers, automated pressure vessels & sealed storage units.',
    image: 'https://images.unsplash.com/photo-1544816155-12df9643f363?auto=format&fit=crop&w=800&q=80',
    productCount: 4,
    active: true,
    sortOrder: 1,
  },
  {
    id: 'cat-2',
    name: 'Clothing',
    slug: 'clothing',
    description: 'Bespoke tailoring, long-staple Giza cotton shirting, and luxury minimalist lounge wear.',
    image: 'https://images.unsplash.com/photo-1596755094514-f87e34085b2c?auto=format&fit=crop&w=800&q=80',
    productCount: 4,
    active: true,
    sortOrder: 2,
  },
  {
    id: 'cat-3',
    name: 'T-Shirt Combo',
    slug: 't-shirt-combo',
    description: 'Curated 2-pack & 3-pack heavyweight combed cotton essentials with seamless silhouettes.',
    image: 'https://images.unsplash.com/photo-1521572267360-ee0c2909d518?auto=format&fit=crop&w=800&q=80',
    productCount: 3,
    active: true,
    sortOrder: 3,
  },
  {
    id: 'cat-4',
    name: 'Health',
    slug: 'health',
    description: 'Bioavailable liposomal solutions, clean electrolytes, and botanical adaptogens.',
    image: 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?auto=format&fit=crop&w=800&q=80',
    productCount: 3,
    active: true,
    sortOrder: 4,
  },
  {
    id: 'cat-5',
    name: 'Organics',
    slug: 'organics',
    description: 'Direct-farm single-origin raw honey, virgin cold-pressed oils, and artisanal whole foods.',
    image: 'https://images.unsplash.com/photo-1587049352846-4a222e784d38?auto=format&fit=crop&w=800&q=80',
    productCount: 3,
    active: true,
    sortOrder: 5,
  },
  {
    id: 'cat-6',
    name: 'Medicines',
    slug: 'medicines',
    description: 'Essential OTC pharmacy preparations, electrolyte oral rehydration & botanical lozenges.',
    image: 'https://images.unsplash.com/photo-1471864190281-a93a3070b6de?auto=format&fit=crop&w=800&q=80',
    productCount: 3,
    active: true,
    sortOrder: 6,
  },
];

export const DEFAULT_PRODUCTS: Product[] = [
  // 1. COOKER & RICE ITEMS
  {
    id: 'prod-cooker-1',
    name: 'Velora Master-IH Smart Digital Multi-Cooker',
    slug: 'velora-master-ih-smart-digital-multi-cooker',
    category: 'Cooker & Rice Items',
    description: 'Engineered with 360-degree electromagnetic induction heating and a 5-layer aerospace ceramic inner pot. Includes 16 micro-programmed pressure profiles, fuzzy logic temperature calibration, and high-tensile brushed graphite stainless steel housing.',
    shortDescription: 'Flagship 5L Smart Induction multi-cooker with ceramic inner pot and precision pressure.',
    regularPrice: 12500,
    salePrice: 9450,
    stock: 24,
    sku: 'VEL-CKR-001',
    brand: 'VELORA APPLIANCES',
    images: [
      'https://images.unsplash.com/photo-1584269600464-37b1b58a9fe7?auto=format&fit=crop&w=900&q=80',
      'https://images.unsplash.com/photo-1544816155-12df9643f363?auto=format&fit=crop&w=900&q=80',
      'https://images.unsplash.com/photo-1556911220-e15b29be8c8f?auto=format&fit=crop&w=900&q=80',
    ],
    variants: ['5-Liter Family Edition', '3-Liter Compact Edition'],
    colors: [
      { name: 'Brushed Obsidian', hex: '#1c1d22' },
      { name: 'Champagne Titanium', hex: '#8c8273' },
      { name: 'Pearl Matte White', hex: '#e8e8e8' },
    ],
    specifications: {
      'Heating Method': '3D Induction Heating (IH)',
      'Capacity': '5.0 Liters / 10 Cups Cooked',
      'Power Rating': '1350W Super-Conductive Coil',
      'Inner Bowl': '5-Layer Diamond Ceramic Shield',
      'Display': 'OLED Hidden Touch Interface',
      'Warranty': '3 Years International Replacement',
    },
    featured: true,
    bestseller: true,
    newArrival: false,
    active: true,
    rating: 4.9,
    reviewsCount: 148,
    createdAt: '2026-01-15T08:00:00.000Z',
    model3dType: 'cooker',
  },
  {
    id: 'prod-cooker-2',
    name: 'Precision Micro-Computer Ceramic Rice Cooker',
    slug: 'precision-micro-computer-ceramic-rice-cooker',
    category: 'Cooker & Rice Items',
    description: 'Crafted for connoisseurs of Jasmine, Basmati, and Brown grains. Features spherical curvature heat distribution that locks in natural starch sweetness and prevents crusting.',
    shortDescription: 'Spherical inner pot rice cooker with 24h thermal preservation.',
    regularPrice: 7800,
    salePrice: 6200,
    stock: 18,
    sku: 'VEL-CKR-002',
    brand: 'VELORA APPLIANCES',
    images: [
      'https://images.unsplash.com/photo-1544816155-12df9643f363?auto=format&fit=crop&w=900&q=80',
      'https://images.unsplash.com/photo-1584269600464-37b1b58a9fe7?auto=format&fit=crop&w=900&q=80',
    ],
    variants: ['3-Liter Standard', '4-Liter Plus'],
    colors: [
      { name: 'Pure White Ceramic', hex: '#f0f0f0' },
      { name: 'Midnight Charcoal', hex: '#23252a' },
    ],
    specifications: {
      'Capacity': '3.0 Liters',
      'Power': '860W',
      'Presets': 'Quick Cook, Congee, Claypot, Cake, Steaming',
    },
    featured: true,
    bestseller: false,
    newArrival: true,
    active: true,
    rating: 4.8,
    reviewsCount: 89,
    createdAt: '2026-02-10T10:00:00.000Z',
    model3dType: 'cooker',
  },
  {
    id: 'prod-cooker-3',
    name: 'Smart 12-in-1 Electric Pressure Vessel',
    slug: 'smart-12-in-1-electric-pressure-vessel',
    category: 'Cooker & Rice Items',
    description: 'Instant whisper-quiet auto steam release mechanism. Slow cooking, high pressure braising, sous-vide, and rice modes all in one sleek appliance.',
    shortDescription: 'Automated pressure vessel with whisper steam discharge system.',
    regularPrice: 11000,
    salePrice: 8900,
    stock: 12,
    sku: 'VEL-CKR-003',
    brand: 'VELORA APPLIANCES',
    images: [
      'https://images.unsplash.com/photo-1556911220-e15b29be8c8f?auto=format&fit=crop&w=900&q=80',
      'https://images.unsplash.com/photo-1584269600464-37b1b58a9fe7?auto=format&fit=crop&w=900&q=80',
    ],
    variants: ['6-Liter Pro Vessel'],
    colors: [
      { name: 'Gunmetal Stainless', hex: '#3d4048' },
    ],
    specifications: {
      'Working Pressure': '80kPa Dual Chamber',
      'Safety Locks': '9-Tier Redundant Sensor Shield',
    },
    featured: false,
    bestseller: false,
    newArrival: false,
    active: true,
    rating: 4.7,
    reviewsCount: 62,
    createdAt: '2026-02-14T09:00:00.000Z',
    model3dType: 'cooker',
  },
  {
    id: 'prod-cooker-4',
    name: 'Airtight Vacuum Rice & Grain Dispenser (15kg)',
    slug: 'airtight-vacuum-rice-grain-dispenser',
    category: 'Cooker & Rice Items',
    description: 'Medical-grade BPA-free borosilicate and matte polymer grain silo with one-touch calibrated 150g cup measuring drawer and moisture desiccant cartridge.',
    shortDescription: '15kg smart metered rice storage vault with humidity sealing.',
    regularPrice: 3800,
    salePrice: 2950,
    stock: 45,
    sku: 'VEL-CKR-004',
    brand: 'VELORA APPLIANCES',
    images: [
      'https://images.unsplash.com/photo-1585515320310-259814833e62?auto=format&fit=crop&w=900&q=80',
    ],
    variants: ['15 Kilogram Capacity', '10 Kilogram Slim'],
    colors: [
      { name: 'Smoked Anthracite', hex: '#2b2c34' },
      { name: 'Frosted Alabaster', hex: '#e9ecef' },
    ],
    specifications: {
      'Volume': '15 KG Gross Storage',
      'Seal Type': 'Double Silicone Hermetic Gasket',
    },
    featured: false,
    bestseller: true,
    newArrival: false,
    active: true,
    rating: 4.9,
    reviewsCount: 114,
    createdAt: '2026-02-01T12:00:00.000Z',
    model3dType: 'cooker',
  },

  // 2. CLOTHING
  {
    id: 'prod-cloth-1',
    name: 'Giza-87 Long-Staple Cotton Tailored Shirt',
    slug: 'giza-87-long-staple-cotton-tailored-shirt',
    category: 'Clothing',
    description: 'Woven from hand-selected extra-long staple Egyptian Giza cotton. Features natural Australian mother-of-pearl buttons, single-needle French seam stitching, and a semi-spread luxury collar.',
    shortDescription: 'Ultra-luxurious 120s 2-ply Egyptian cotton shirting with natural luster.',
    regularPrice: 4200,
    salePrice: 3400,
    stock: 35,
    sku: 'VEL-CLT-001',
    brand: 'VELORA ATELIER',
    images: [
      'https://images.unsplash.com/photo-1596755094514-f87e34085b2c?auto=format&fit=crop&w=900&q=80',
      'https://images.unsplash.com/photo-1602810318383-e386cc2a3ccf?auto=format&fit=crop&w=900&q=80',
    ],
    sizes: ['S (38)', 'M (40)', 'L (42)', 'XL (44)', 'XXL (46)'],
    colors: [
      { name: 'Crisp White', hex: '#ffffff' },
      { name: 'Sky Celeste Blue', hex: '#b3d4f0' },
      { name: 'Midnight Navy', hex: '#0f172a' },
    ],
    specifications: {
      'Material': '100% Giza-87 Long Staple Egyptian Cotton',
      'Weave': '120/2 Compact Poplin',
      'Buttons': 'Carved Mother of Pearl',
      'Fit': 'Contemporary Tailored Fit',
    },
    featured: true,
    bestseller: true,
    newArrival: false,
    active: true,
    rating: 4.9,
    reviewsCount: 96,
    createdAt: '2026-01-20T11:00:00.000Z',
    model3dType: 'tshirt',
  },
  {
    id: 'prod-cloth-2',
    name: 'Relaxed Italian Linen Resort Overshirt',
    slug: 'relaxed-italian-linen-resort-overshirt',
    category: 'Clothing',
    description: 'Enzyme-washed European flax linen offering unmatched breathability and a softly draped silhouette. Perfect for tropical climates and evening dining.',
    shortDescription: 'Pre-washed pure European linen overshirt with chest flap pockets.',
    regularPrice: 3800,
    salePrice: 2950,
    stock: 22,
    sku: 'VEL-CLT-002',
    brand: 'VELORA ATELIER',
    images: [
      'https://images.unsplash.com/photo-1602810318383-e386cc2a3ccf?auto=format&fit=crop&w=900&q=80',
      'https://images.unsplash.com/photo-1596755094514-f87e34085b2c?auto=format&fit=crop&w=900&q=80',
    ],
    sizes: ['M (40)', 'L (42)', 'XL (44)'],
    colors: [
      { name: 'Natural Sand', hex: '#d9cdb8' },
      { name: 'Olive Drab', hex: '#556b2f' },
      { name: 'Deep Onyx', hex: '#18181b' },
    ],
    specifications: {
      'Fabric': '100% Certified European Flax Linen',
      'Weight': '180 GSM Pre-Softened',
    },
    featured: false,
    bestseller: false,
    newArrival: true,
    active: true,
    rating: 4.8,
    reviewsCount: 42,
    createdAt: '2026-02-18T14:00:00.000Z',
    model3dType: 'tshirt',
  },
  {
    id: 'prod-cloth-3',
    name: 'Heavyweight Loopback French Terry Sweatshirt',
    slug: 'heavyweight-loopback-french-terry-sweatshirt',
    category: 'Clothing',
    description: '450 GSM combed cotton loopback fleece crafted on vintage circular knitting looms. Raglan sleeve construction with resilient ribbed cuffs and hem.',
    shortDescription: '450 GSM luxury architectural crewneck sweater.',
    regularPrice: 3200,
    salePrice: 2600,
    stock: 28,
    sku: 'VEL-CLT-003',
    brand: 'VELORA ATELIER',
    images: [
      'https://images.unsplash.com/photo-1578587018452-892bacefd3f2?auto=format&fit=crop&w=900&q=80',
    ],
    sizes: ['S', 'M', 'L', 'XL'],
    colors: [
      { name: 'Heather Concrete', hex: '#9ca3af' },
      { name: 'Pitch Black', hex: '#0a0a0a' },
    ],
    specifications: {
      'Weight': '450 GSM Heavy French Terry',
      'Yarn': 'Combed Ringspun Organic Cotton',
    },
    featured: false,
    bestseller: false,
    newArrival: false,
    active: true,
    rating: 4.9,
    reviewsCount: 53,
    createdAt: '2026-01-10T16:00:00.000Z',
    model3dType: 'tshirt',
  },
  {
    id: 'prod-cloth-4',
    name: 'Pleated Minimalist Tencel Relaxed Trouser',
    slug: 'pleated-minimalist-tencel-relaxed-trouser',
    category: 'Clothing',
    description: 'Eco-conscious Lyocell Tencel blend offering a fluid liquid-like drape, subtle double front pleats, and an elasticated concealed waistband.',
    shortDescription: 'Fluid drape pleated trouser with concealed drawstring comfort.',
    regularPrice: 3600,
    salePrice: 2850,
    stock: 19,
    sku: 'VEL-CLT-004',
    brand: 'VELORA ATELIER',
    images: [
      'https://images.unsplash.com/photo-1479064555552-3ef4979f8908?auto=format&fit=crop&w=900&q=80',
    ],
    sizes: ['30', '32', '34', '36'],
    colors: [
      { name: 'Charcoal Slate', hex: '#334155' },
      { name: 'Warm Taupe', hex: '#78716c' },
    ],
    specifications: {
      'Composition': '70% Austrian Tencel Lyocell, 30% Fine Cotton',
    },
    featured: false,
    bestseller: false,
    newArrival: false,
    active: true,
    rating: 4.7,
    reviewsCount: 38,
    createdAt: '2026-02-05T12:00:00.000Z',
    model3dType: 'tshirt',
  },

  // 3. T-SHIRT COMBO
  {
    id: 'prod-tcombo-1',
    name: 'Velora Signature Duo-Pack (2 Heavyweight Tees)',
    slug: 'velora-signature-duo-pack-2-heavyweight-tees',
    category: 'T-Shirt Combo',
    description: 'The definitive daily luxury tee bundle. Two 260 GSM combed compact cotton tees with reinforced collar ribbing that will never bacon or deform. Boxy contemporary streetwear cut.',
    shortDescription: 'Set of 2 Heavyweight 260 GSM boxy minimalist luxury tees.',
    regularPrice: 2400,
    salePrice: 1850,
    stock: 65,
    sku: 'VEL-TSH-001',
    brand: 'VELORA BASICS',
    images: [
      'https://images.unsplash.com/photo-1521572267360-ee0c2909d518?auto=format&fit=crop&w=900&q=80',
      'https://images.unsplash.com/photo-1583743814966-8936f5b7be1a?auto=format&fit=crop&w=900&q=80',
    ],
    sizes: ['M (Chest 40)', 'L (Chest 42)', 'XL (Chest 44)', 'XXL (Chest 46)'],
    colors: [
      { name: 'Monochrome Pack (1 Black + 1 White)', hex: '#000000' },
      { name: 'Earth Pack (1 Olive + 1 Sand)', hex: '#556b2f' },
      { name: 'Double Shadow (2 Deep Black)', hex: '#111111' },
    ],
    specifications: {
      'Included': '2 Premium T-Shirts in Rigid Matte Gift Box',
      'Weight': '260 GSM Interlock Combed Cotton',
      'Neckline': '2.5cm Lycra Reinforced Seamless Ribbing',
      'Shrinkage': 'Pre-Shrunk & Silicone Softened',
    },
    featured: true,
    bestseller: true,
    newArrival: false,
    active: true,
    rating: 5.0,
    reviewsCount: 284,
    createdAt: '2026-01-05T09:00:00.000Z',
    model3dType: 'tshirt',
  },
  {
    id: 'prod-tcombo-2',
    name: 'Tri-Blend Minimalist Everyday Trio (3-Pack)',
    slug: 'tri-blend-minimalist-everyday-trio-3-pack',
    category: 'T-Shirt Combo',
    description: 'Three exceptionally soft daily crewnecks formulated with 95% supima cotton and 5% elastane memory fiber. Breathable, sweat-wicking, and color-fast after 100+ washes.',
    shortDescription: '3-Piece curated essentials pack in Black, Heather Gray, and Ivory.',
    regularPrice: 3300,
    salePrice: 2450,
    stock: 48,
    sku: 'VEL-TSH-002',
    brand: 'VELORA BASICS',
    images: [
      'https://images.unsplash.com/photo-1583743814966-8936f5b7be1a?auto=format&fit=crop&w=900&q=80',
      'https://images.unsplash.com/photo-1521572267360-ee0c2909d518?auto=format&fit=crop&w=900&q=80',
    ],
    sizes: ['S', 'M', 'L', 'XL'],
    colors: [
      { name: 'Core Triad (Black, Slate Gray, Pure White)', hex: '#374151' },
    ],
    specifications: {
      'Included': '3 Luxury T-Shirts',
      'Weight': '220 GSM Supima Stretch',
    },
    featured: true,
    bestseller: false,
    newArrival: true,
    active: true,
    rating: 4.8,
    reviewsCount: 119,
    createdAt: '2026-02-12T13:00:00.000Z',
    model3dType: 'tshirt',
  },
  {
    id: 'prod-tcombo-3',
    name: 'Minimalist Couple T-Shirt Matching Set (2-Piece)',
    slug: 'minimalist-couple-t-shirt-matching-set',
    category: 'T-Shirt Combo',
    description: 'Elegantly synchronized His & Hers premium drop-shoulder t-shirts with discreet tonal micro-embroidery at the chest hem. Packaged in satin-finish keepsake envelope.',
    shortDescription: 'Complementary tonal drop-shoulder matching set for couples.',
    regularPrice: 2600,
    salePrice: 2100,
    stock: 30,
    sku: 'VEL-TSH-003',
    brand: 'VELORA BASICS',
    images: [
      'https://images.unsplash.com/photo-1503342217505-b0a15ec3261c?auto=format&fit=crop&w=900&q=80',
    ],
    sizes: ['His L + Her M', 'His XL + Her S', 'His M + Her S', 'His XL + Her M'],
    colors: [
      { name: 'Matcha Latte & Cream', hex: '#a3b18a' },
      { name: 'Obsidian & Chalk', hex: '#1e293b' },
    ],
    specifications: {
      'Included': '1 Men Fit Tee + 1 Women Drop-Shoulder Tee',
    },
    featured: false,
    bestseller: false,
    newArrival: true,
    active: true,
    rating: 4.9,
    reviewsCount: 75,
    createdAt: '2026-02-19T10:00:00.000Z',
    model3dType: 'tshirt',
  },

  // 4. HEALTH
  {
    id: 'prod-hlth-1',
    name: 'Nano-Liposomal CoQ10 & Zinc Vitality Elixir (60ml)',
    slug: 'nano-liposomal-coq10-zinc-vitality-elixir',
    category: 'Health',
    description: 'High-absorption cellular mitochondrial booster formulated with pharmaceutical-grade phospholipid nano-spheres for up to 8x higher bioavailability compared to crystalline powders.',
    shortDescription: 'Advanced cellular energy and immunity sublingual drops.',
    regularPrice: 2850,
    salePrice: 2250,
    stock: 40,
    sku: 'VEL-HLT-001',
    brand: 'VELORA BIO-LABS',
    images: [
      'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?auto=format&fit=crop&w=900&q=80',
      'https://images.unsplash.com/photo-1584017911766-d451b3d0e843?auto=format&fit=crop&w=900&q=80',
    ],
    specifications: {
      'Serving Size': '1ml (approx. 20 drops)',
      'Dosage': 'CoQ10 Ubiquinol 100mg + Zinc Picolinate 15mg',
      'Volume': '60ml Amber Glass Dropper (60 Servings)',
    },
    isMedicineOrHealth: true,
    manufacturer: 'Velora Clinical Sciences Ltd., ISO 22000 Certified',
    ingredients: 'Phosphatidylcholine (Sunflower Non-GMO), Ubiquinol (Kaneka QH™), Zinc Picolinate, Organic Citrus Terpenes, Vegetable Glycerin.',
    usageInstructions: 'Take 1ml daily held under tongue for 30 seconds before swallowing, preferably with morning meal.',
    warnings: 'Food supplement. Not for use as a substitute for a varied diet. Consult physician if pregnant or under medical treatment.',
    expiryDate: '2027-12-31',
    batchNumber: 'VBL-2026-098K',
    featured: true,
    bestseller: true,
    newArrival: false,
    active: true,
    rating: 4.9,
    reviewsCount: 167,
    createdAt: '2026-01-12T10:00:00.000Z',
    model3dType: 'bottle',
  },
  {
    id: 'prod-hlth-2',
    name: 'Ultra-Pure Deep Sea Omega-3 Triglycerides',
    slug: 'ultra-pure-deep-sea-omega-3-triglycerides',
    category: 'Health',
    description: 'Molecularly distilled wild anchovy and sardine oil delivering 800mg EPA and 400mg DHA per softgel. Certified IFOS 5-Star for zero heavy metal toxicity and oxidation freshness.',
    shortDescription: '1200mg active EPA/DHA softgels with natural lemon essence.',
    regularPrice: 2400,
    salePrice: 1950,
    stock: 52,
    sku: 'VEL-HLT-002',
    brand: 'VELORA BIO-LABS',
    images: [
      'https://images.unsplash.com/photo-1584017911766-d451b3d0e843?auto=format&fit=crop&w=900&q=80',
    ],
    specifications: {
      'Count': '90 Enteric Softgels',
      'Purity Standard': 'IFOS 5-Star Certified Heavy Metal Free',
    },
    isMedicineOrHealth: true,
    manufacturer: 'Velora Clinical Sciences Ltd.',
    ingredients: 'Purified Deep Sea Fish Oil (Triglyceride Form), Gelatin, Purified Water, Rosemary Leaf Extract, Natural D-Alpha Tocopherol.',
    usageInstructions: 'Take 2 softgels daily with water after lunch or dinner.',
    warnings: 'Contains fish derivatives. Keep out of reach of children. Store below 25°C in a dry place.',
    expiryDate: '2028-03-31',
    batchNumber: 'OM3-7721-BC',
    featured: false,
    bestseller: true,
    newArrival: false,
    active: true,
    rating: 4.8,
    reviewsCount: 88,
    createdAt: '2026-01-25T15:00:00.000Z',
    model3dType: 'bottle',
  },
  {
    id: 'prod-hlth-3',
    name: 'Electrolyte Balance Zero-Sugar Hydration Sticks (30ct)',
    slug: 'electrolyte-balance-zero-sugar-hydration-sticks',
    category: 'Health',
    description: 'Precision osmotic hydration formulation based on WHO standards. Rapid cellular fluid absorption with 1000mg sodium, 200mg potassium, and 60mg magnesium malate.',
    shortDescription: 'Clean ionic hydration sticks with real raspberry extract.',
    regularPrice: 1800,
    salePrice: 1450,
    stock: 38,
    sku: 'VEL-HLT-003',
    brand: 'VELORA BIO-LABS',
    images: [
      'https://images.unsplash.com/photo-1577401239170-897942555fb3?auto=format&fit=crop&w=900&q=80',
    ],
    specifications: {
      'Quantity': '30 Individual Single-Serve Packets',
      'Sweetener': 'Pure Stevia Leaf Extract (Zero Glycemic)',
    },
    isMedicineOrHealth: true,
    manufacturer: 'Velora Clinical Sciences Ltd.',
    ingredients: 'Sodium Chloride, Potassium Citrate, Magnesium Malate, Citric Acid, Natural Fruit Flavor, Steviol Glycosides.',
    usageInstructions: 'Mix 1 packet into 500ml cold water. Consume during workout, travel, or hot weather.',
    warnings: 'Individuals with kidney disease or salt-restricted regimens should consult a physician.',
    expiryDate: '2027-10-15',
    batchNumber: 'ELX-3012-HYD',
    featured: false,
    bestseller: false,
    newArrival: true,
    active: true,
    rating: 4.9,
    reviewsCount: 46,
    createdAt: '2026-02-15T09:00:00.000Z',
    model3dType: 'bottle',
  },

  // 5. ORGANICS
  {
    id: 'prod-org-1',
    name: 'Sundarbans Artisanal Raw Wild Forest Honey (500g)',
    slug: 'sundarbans-artisanal-raw-wild-forest-honey',
    category: 'Organics',
    description: 'Sustainably harvested from deep inside the mangrove biosphere reserve by traditional Mawali foragers. Unheated, raw, unpasteurized, and rich in natural pollen, royal jelly enzymes, and antioxidants.',
    shortDescription: 'Unfiltered, raw mangrove honey with wild floral complexity.',
    regularPrice: 1650,
    salePrice: 1250,
    stock: 55,
    sku: 'VEL-ORG-001',
    brand: 'VELORA HARVESTS',
    images: [
      'https://images.unsplash.com/photo-1587049352846-4a222e784d38?auto=format&fit=crop&w=900&q=80',
      'https://images.unsplash.com/photo-1558642452-9d2a7deb7f62?auto=format&fit=crop&w=900&q=80',
    ],
    variants: ['500 Gram Luxury Jar', '1000 Gram Reserve Silo'],
    specifications: {
      'Origin': 'Sundarbans Mangrove Biosphere, Bangladesh',
      'Processing': 'Cold-Strained, 100% Unpasteurized',
      'Packaging': 'Heavy Italian UV-blocking Amber Glass',
      'Moisture Content': 'Under 18.5% (High Density Premium Grade)',
    },
    isMedicineOrHealth: true,
    manufacturer: 'Velora Agro Organics Co-op',
    ingredients: '100% Pure Wild Forest Honey (Apis Dorsata)',
    usageInstructions: 'Enjoy 1-2 teaspoons directly or stirred into warm tea or breakfast oats.',
    warnings: 'Do not feed raw honey to infants under 12 months of age. Store in a cool dry place.',
    expiryDate: '2028-12-31',
    batchNumber: 'SND-HON-2026',
    featured: true,
    bestseller: true,
    newArrival: false,
    active: true,
    rating: 5.0,
    reviewsCount: 312,
    createdAt: '2026-01-08T07:00:00.000Z',
    model3dType: 'bottle',
  },
  {
    id: 'prod-org-2',
    name: 'First-Flush Organic Himalayan Ceremonial Matcha (50g)',
    slug: 'first-flush-organic-himalayan-ceremonial-matcha',
    category: 'Organics',
    description: 'Stone-ground ceremonial grade green tea powder from shade-grown spring leaves. Vibrant electric jade green hue with an intensely sweet, umami-rich finish and high L-theanine calming focus.',
    shortDescription: 'Single-estate stone ground stone-milled ceremonial green tea.',
    regularPrice: 2200,
    salePrice: 1750,
    stock: 25,
    sku: 'VEL-ORG-002',
    brand: 'VELORA HARVESTS',
    images: [
      'https://images.unsplash.com/photo-1576092768241-dec231879fc3?auto=format&fit=crop&w=900&q=80',
    ],
    specifications: {
      'Harvest': 'Spring First Flush Shade-Grown',
      'Grind': 'Traditional Granite Stone Wheel',
      'Weight': '50 Gram Sealed Oxygen-Free Tin',
    },
    isMedicineOrHealth: true,
    manufacturer: 'Velora Agro Organics',
    ingredients: '100% Organic Camellia Sinensis Leaf Powder',
    usageInstructions: 'Whisk 1.5g with 70ml hot water (80°C) until a velvety jade foam forms.',
    warnings: 'Contains natural caffeine. Keep sealed in refrigerator after opening.',
    expiryDate: '2027-08-30',
    batchNumber: 'MTC-8891-EST',
    featured: true,
    bestseller: false,
    newArrival: true,
    active: true,
    rating: 4.9,
    reviewsCount: 78,
    createdAt: '2026-02-08T11:00:00.000Z',
    model3dType: 'bottle',
  },
  {
    id: 'prod-org-3',
    name: 'Cold-Pressed Virgin Yellow Mustard Oil (1 Liter)',
    slug: 'cold-pressed-virgin-yellow-mustard-oil',
    category: 'Organics',
    description: 'Extracted using traditional wooden Ghani expellers at temperatures below 38°C to retain natural pungency, vital Omega-6/Omega-3 ratio, and rich golden aroma.',
    shortDescription: 'Traditional wooden cold-pressed virgin seed oil.',
    regularPrice: 850,
    salePrice: 680,
    stock: 80,
    sku: 'VEL-ORG-003',
    brand: 'VELORA HARVESTS',
    images: [
      'https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?auto=format&fit=crop&w=900&q=80',
    ],
    specifications: {
      'Extraction': 'Wood Cold-Pressed (Khol Ghani)',
      'Volume': '1000 ml Food-Grade Tin Container',
    },
    isMedicineOrHealth: true,
    manufacturer: 'Velora Agro Organics',
    ingredients: '100% First-Press Non-GMO Yellow Mustard Seeds',
    usageInstructions: 'Ideal for authentic South Asian cooking, salad dressings, and culinary seasoning.',
    warnings: 'For culinary use. Store in dark cool pantry away from direct sunlight.',
    expiryDate: '2027-06-30',
    batchNumber: 'MST-3341-VG',
    featured: false,
    bestseller: true,
    newArrival: false,
    active: true,
    rating: 4.9,
    reviewsCount: 142,
    createdAt: '2026-01-18T14:00:00.000Z',
    model3dType: 'bottle',
  },

  // 6. MEDICINES (Compliant Demo Products clearly marked)
  {
    id: 'prod-med-1',
    name: 'Probio-Shield 50 Billion CFU Multi-Strain Probiotic [Demo]',
    slug: 'probio-shield-50-billion-cfu-multi-strain-probiotic',
    category: 'Medicines',
    description: 'DEMO SAMPLE PRODUCT. Formulated with 12 clinically researched probiotic strains and prebiotic FOS in delayed-release vegetarian capsules that bypass stomach acid intact.',
    shortDescription: 'DEMO PRODUCT: 12-strain microencapsulated gastrointestinal support.',
    regularPrice: 2200,
    salePrice: 1750,
    stock: 34,
    sku: 'VEL-MED-001',
    brand: 'VELORA PHARMA (DEMO)',
    images: [
      'https://images.unsplash.com/photo-1471864190281-a93a3070b6de?auto=format&fit=crop&w=900&q=80',
      'https://images.unsplash.com/photo-1584017911766-d451b3d0e843?auto=format&fit=crop&w=900&q=80',
    ],
    specifications: {
      'Strength': '50 Billion Live CFUs at Expiry',
      'Capsules': '60 Delayed-Release DRcaps®',
    },
    isMedicineOrHealth: true,
    prescriptionRequired: false,
    manufacturer: 'Velora Healthcare Diagnostics Ltd. (Demonstration)',
    ingredients: 'Lactobacillus acidophilus, Bifidobacterium lactis, Fructooligosaccharides (FOS), Plant Cellulose.',
    usageInstructions: 'Take 1 capsule daily on an empty stomach or with a light meal.',
    warnings: 'DEMO PRODUCT NOTICE: Not intended to diagnose, treat, cure, or prevent any illness. Consult licensed physician for medical guidance.',
    expiryDate: '2027-11-30',
    batchNumber: 'MED-DEMO-9912',
    featured: false,
    bestseller: false,
    newArrival: true,
    active: true,
    rating: 4.8,
    reviewsCount: 39,
    createdAt: '2026-02-11T16:00:00.000Z',
    model3dType: 'bottle',
  },
  {
    id: 'prod-med-2',
    name: 'Botanical Throat Comfort Lozenges with Propolis [Demo]',
    slug: 'botanical-throat-comfort-lozenges-with-propolis',
    category: 'Medicines',
    description: 'DEMO SAMPLE PRODUCT. Soothing herbal pastilles with certified raw propolis, eucalyptus oil, menthol, and raw organic honey to ease vocal strain and seasonal irritation.',
    shortDescription: 'DEMO PRODUCT: Natural bee propolis and menthol throat pastilles.',
    regularPrice: 750,
    salePrice: 580,
    stock: 75,
    sku: 'VEL-MED-002',
    brand: 'VELORA PHARMA (DEMO)',
    images: [
      'https://images.unsplash.com/photo-1550572017-edd951aa8f72?auto=format&fit=crop&w=900&q=80',
    ],
    specifications: {
      'Count': '24 Individually Wrapped Lozenges',
    },
    isMedicineOrHealth: true,
    prescriptionRequired: false,
    manufacturer: 'Velora Healthcare Diagnostics Ltd. (Demonstration)',
    ingredients: 'Bee Propolis Extract, Menthol, Organic Honey, Eucalyptus Essential Oil, Isomalt.',
    usageInstructions: 'Slowly dissolve 1 lozenge in mouth as needed up to 5 times per day.',
    warnings: 'DEMO PRODUCT NOTICE: Individuals with bee or propolis allergies must avoid use.',
    expiryDate: '2028-02-28',
    batchNumber: 'TH-LOZ-5501',
    featured: false,
    bestseller: false,
    newArrival: false,
    active: true,
    rating: 4.9,
    reviewsCount: 51,
    createdAt: '2026-01-30T10:00:00.000Z',
    model3dType: 'bottle',
  },
  {
    id: 'prod-med-3',
    name: 'WHO-Compliant Oral Rehydration Salts (ORS 20ct) [Demo]',
    slug: 'who-compliant-oral-rehydration-salts',
    category: 'Medicines',
    description: 'DEMO SAMPLE PRODUCT. Standard reduced-osmolarity electrolyte formulation designed in accordance with World Health Organization guidelines for rapid restoration of fluid balance.',
    shortDescription: 'DEMO PRODUCT: Standard osmotic oral rehydration therapy packets.',
    regularPrice: 500,
    salePrice: 390,
    stock: 120,
    sku: 'VEL-MED-003',
    brand: 'VELORA PHARMA (DEMO)',
    images: [
      'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?auto=format&fit=crop&w=900&q=80',
    ],
    specifications: {
      'Quantity': '20 Packets (Each yields 500ml oral solution)',
    },
    isMedicineOrHealth: true,
    prescriptionRequired: false,
    manufacturer: 'Velora Healthcare Diagnostics Ltd. (Demonstration)',
    ingredients: 'Sodium Chloride, Potassium Chloride, Trisodium Citrate, Anhydrous Glucose.',
    usageInstructions: 'Dissolve contents of one sachet in exactly 500ml of clean drinking water.',
    warnings: 'DEMO PRODUCT: Do not boil the prepared solution. Discard unused solution after 24 hours.',
    expiryDate: '2028-05-31',
    batchNumber: 'ORS-WHO-0021',
    featured: false,
    bestseller: false,
    newArrival: false,
    active: true,
    rating: 4.9,
    reviewsCount: 44,
    createdAt: '2026-02-01T08:00:00.000Z',
    model3dType: 'bottle',
  },
];

export const DEFAULT_COUPONS: Coupon[] = [
  {
    id: 'coup-1',
    code: 'VELORA10',
    discountType: 'percentage',
    discountValue: 10,
    minOrder: 1500,
    maxDiscount: 1000,
    startDate: '2026-01-01',
    endDate: '2026-12-31',
    active: true,
  },
  {
    id: 'coup-2',
    code: 'FIRSTLUXE',
    discountType: 'fixed',
    discountValue: 300,
    minOrder: 2000,
    maxDiscount: 300,
    startDate: '2026-01-01',
    endDate: '2026-12-31',
    active: true,
  },
  {
    id: 'coup-3',
    code: 'VIP500',
    discountType: 'fixed',
    discountValue: 500,
    minOrder: 4000,
    maxDiscount: 500,
    startDate: '2026-01-01',
    endDate: '2026-12-31',
    active: true,
  },
];

export const DEFAULT_CUSTOMERS: Customer[] = [
  {
    id: 'cust-1',
    name: 'Tanvir Hossain',
    phone: '+880 1711-234567',
    email: 'tanvir.h@gmail.com',
    totalOrders: 4,
    totalSpending: 28400,
    lastOrderDate: '2026-02-22T14:30:00.000Z',
    status: 'active',
    createdAt: '2026-01-10T11:00:00.000Z',
  },
  {
    id: 'cust-2',
    name: 'Farhana Rahman',
    phone: '+880 1819-876543',
    email: 'farhana.r@hotmail.com',
    totalOrders: 2,
    totalSpending: 12850,
    lastOrderDate: '2026-02-18T10:15:00.000Z',
    status: 'active',
    createdAt: '2026-01-14T09:30:00.000Z',
  },
  {
    id: 'cust-3',
    name: 'Zubair Ahmed',
    phone: '+880 1912-345678',
    email: 'zubair.ahmed@yahoo.com',
    totalOrders: 1,
    totalSpending: 9450,
    lastOrderDate: '2026-02-24T18:00:00.000Z',
    status: 'active',
    createdAt: '2026-02-24T17:45:00.000Z',
  },
];

export const DEFAULT_ORDERS: Order[] = [
  {
    id: 'VEL-882910',
    customerName: 'Tanvir Hossain',
    phone: '+880 1711-234567',
    email: 'tanvir.h@gmail.com',
    fullAddress: 'House 42, Road 11, Block D, Banani',
    area: 'Banani',
    district: 'Dhaka',
    deliveryNote: 'Please ring bell upon arrival.',
    items: [
      {
        productId: 'prod-cooker-1',
        productName: 'Velora Master-IH Smart Digital Multi-Cooker',
        productImage: 'https://images.unsplash.com/photo-1584269600464-37b1b58a9fe7?auto=format&fit=crop&w=900&q=80',
        price: 9450,
        quantity: 1,
        selectedVariant: '5-Liter Family Edition',
        selectedColor: 'Brushed Obsidian',
      },
      {
        productId: 'prod-org-1',
        productName: 'Sundarbans Artisanal Raw Wild Forest Honey (500g)',
        productImage: 'https://images.unsplash.com/photo-1587049352846-4a222e784d38?auto=format&fit=crop&w=900&q=80',
        price: 1250,
        quantity: 1,
        selectedVariant: '500 Gram Luxury Jar',
      },
    ],
    subtotal: 10700,
    deliveryCharge: 60,
    discount: 500,
    total: 10260,
    paymentMethod: 'bkash',
    paymentStatus: 'paid',
    orderStatus: 'Processing',
    internalNotes: 'VIP Customer. Double-bubble wrapped packaging requested.',
    createdAt: '2026-02-22T14:30:00.000Z',
  },
  {
    id: 'VEL-882894',
    customerName: 'Farhana Rahman',
    phone: '+880 1819-876543',
    email: 'farhana.r@hotmail.com',
    fullAddress: 'Apartment 7B, Green Villa, Sector 3, Uttara',
    area: 'Uttara',
    district: 'Dhaka',
    items: [
      {
        productId: 'prod-tcombo-1',
        productName: 'Velora Signature Duo-Pack (2 Heavyweight Tees)',
        productImage: 'https://images.unsplash.com/photo-1521572267360-ee0c2909d518?auto=format&fit=crop&w=900&q=80',
        price: 1850,
        quantity: 1,
        selectedSize: 'L (Chest 42)',
        selectedColor: 'Monochrome Pack (1 Black + 1 White)',
      },
    ],
    subtotal: 1850,
    deliveryCharge: 60,
    discount: 0,
    total: 1910,
    paymentMethod: 'cod',
    paymentStatus: 'pending',
    orderStatus: 'Shipped',
    internalNotes: 'Dispatched via Pathao Express Courier.',
    createdAt: '2026-02-23T11:20:00.000Z',
  },
];

export const DEFAULT_REVIEWS: Review[] = [
  {
    id: 'rev-1',
    productId: 'prod-cooker-1',
    productName: 'Velora Master-IH Smart Digital Multi-Cooker',
    customerName: 'Rafiqul Islam, Executive Chef',
    rating: 5,
    comment: 'The 360-degree induction heating cooks Polao and Biryani grains with unbelievable precision. Absolutely zero hot spots and the ceramic inner pot cleans effortlessly.',
    createdAt: '2026-02-14T10:00:00.000Z',
    approved: true,
  },
  {
    id: 'rev-2',
    productId: 'prod-tcombo-1',
    productName: 'Velora Signature Duo-Pack (2 Heavyweight Tees)',
    customerName: 'Saadman K.',
    rating: 5,
    comment: 'The 260 GSM fabric has substantial weight without feeling suffocating. The collar stays crisp and never sags after machine washing. Worth every penny.',
    createdAt: '2026-02-16T12:00:00.000Z',
    approved: true,
  },
  {
    id: 'rev-3',
    productId: 'prod-org-1',
    productName: 'Sundarbans Artisanal Raw Wild Forest Honey (500g)',
    customerName: 'Dr. Nusrat Jahan',
    rating: 5,
    comment: 'Real mangrove floral notes, thick crystallization at bottom proving it is unadulterated raw honey. Exceptional packaging and rapid delivery.',
    createdAt: '2026-02-18T16:30:00.000Z',
    approved: true,
  },
];

export const DEFAULT_MEDIA: MediaItem[] = [
  {
    id: 'med-1',
    name: 'Smart Induction Cooker Studio Shot',
    url: 'https://images.unsplash.com/photo-1584269600464-37b1b58a9fe7?auto=format&fit=crop&w=900&q=80',
    category: 'products',
    uploadedAt: '2026-01-10T10:00:00.000Z',
    sizeKb: 480,
  },
  {
    id: 'med-2',
    name: 'Minimalist Apparel Studio',
    url: 'https://images.unsplash.com/photo-1521572267360-ee0c2909d518?auto=format&fit=crop&w=900&q=80',
    category: 'products',
    uploadedAt: '2026-01-12T14:00:00.000Z',
    sizeKb: 520,
  },
  {
    id: 'med-3',
    name: 'Wild Honey Jar Amber Luxury',
    url: 'https://images.unsplash.com/photo-1587049352846-4a222e784d38?auto=format&fit=crop&w=900&q=80',
    category: 'products',
    uploadedAt: '2026-01-15T09:00:00.000Z',
    sizeKb: 610,
  },
  {
    id: 'med-4',
    name: 'Luxury Kitchen Atmosphere Hero',
    url: 'https://images.unsplash.com/photo-1544816155-12df9643f363?auto=format&fit=crop&w=1200&q=80',
    category: 'hero',
    uploadedAt: '2026-01-05T12:00:00.000Z',
    sizeKb: 890,
  },
];
